### ISSUE TITLE
ContainerInterface name

### ISSUE THREAD

**Issue by moufmouf** [container-interop/container-interop#1]
So far, we have chosen to call the main interface ReadableContainerInterface.
The rational behind it is that "ContainerInterface" might be too generic.

We thought about "SimpleContainerInterface" but deemed it was too generic.

This thread is open to add new suggestions.

So far, I have just started looking at other languages.

Spring (in the Java world) has a "BeanFactory" interface, with a "getBean" method.

Add other suggestions (or what other frameworks do below)

---

**Edit:**
- summary of options: https://github.com/container-interop/container-interop/wiki/ContainerInterface-name
- vote: https://github.com/container-interop/container-interop/wiki/%231-interface-name:-Vote

**Comment by J7mbo** [comment]
Why is this still being called a container?

**Comment by mnapoli** [comment]
@J7mbo https://github.com/container-interop/container-interop/wiki/%231-interface-name:-Vote

Let's not reopen that discussion as it has already been a lengthy one finished a year ago. You can re-read the whole thread if you want to understand people's opinions.

See also the meta-document: https://github.com/container-interop/container-interop/blob/master/docs/ContainerInterface-meta.md#interface-name

**Comment by moufmouf** [comment]
@J7mbo This issue has been closed for 1 year now. Regarding *container-interop*, the `ContainerInterface` name is settled, as a stable release has been made. The choice of the name has been extensively documented in this thread and in the meta document.

Now, we are trying to move *container-interop* to the PHP-FIG (https://groups.google.com/forum/#!forum/php-fig), so of course, we can discuss naming of the interface of the soon-to-come PSR. I would prefer if you ask this question on the PHP-FIG mailing list rather than in this thread that should remain closed.

Of course, the `ContainerInterface` name is the result of several months of discussion and I think the name that was chosen has been done wisely, through a lot of discussion and a vote, so I'm ready to defend it.

**Comment by J7mbo** [comment]
@moufmouf Actually I'd prefer to be in a *discussion*: Please don't assume that I'm out for an aggressive attack that you have to 'defend' against. I think `ContainerInterface` goes well with *Symfony* devs, and their style of coding, because they love putting "Interface" at the end of everything. But I wholeheartedly disagree with "Container".

The reasons for that are that a container implies something that holds objects - if you place objects in this box, you're already advocating the service locator pattern *and* creating a god object. Let's not even get onto how Laravel names things. Call it a container and we're *really* not progressing in teaching best practice to the PHP community - which is what FIG is supposed to be standing up for.

It should be Injector imho, however the decision has already been made.

**Comment by Ocramius** [comment]
>  think `ContainerInterface` goes well with _Symfony_ devs, and their style of coding, because they love putting "Interface" at the end of everything.

To be honest, most of the people that discussed in this thread have little to do with Symfony anyway.

 > you're already advocating the service locator pattern and creating a god object

Yes, we are. The fact is that the only possible interface for an Injector or a DIC or a Container is indeed a locator. Even in "higher level" libraries having a single location where the injector is used, SL is how this is achieved (see, for example, `$app = $injector->get('app')`, and no other usage of `$injector` - yes, that's SL, get over it).

 > we're _really_ not progressing in teaching best practice to the PHP community

I actually agree with that, but a vote has already been set for the name, even if I disagree with it. From now on it's either accept or reject the proposal for it, and we may reconsider naming if the voting fails, I'd say.

 > which is what FIG is supposed to be standing up for

No, you are confusing http://www.phptherightway.com/ with FIG. FIG is about Framework-Interoperability, which (in other words) means "let's stop stepping on each other work and let's work together", where the `we` in the scope of the sentence is "frameworks" or "libraries", and has nothing to do with end-users. The fact that end-users get shiny things such as `psr-0` is a side-effect.

 > It should be Injector imho

Injector does not apply, mainly because then we'd design an interface for a factory, and tbh, `callable` is already enough for that. Also, factories vary too much between frameworks to actually standardize right now.

If you want to explore the injector concept more, then feel free to write down a **new** proposal that deals with DI configuration/setup and all the details that can be commonly adopted by all frameworks.
A discussion was already started in #27.
I personally disagree with it, but it takes a lot of exploration to actually define how an injector works, and you also have to remember that defining an interface means also that you **cannot dictate any implementation details**, just the consumer API.
You'll see for yourself that it drills down to a locator again, regardless how perfect your injector prototype actually becomes. If that's not the case, then I'd like to see such an interface, as I've also been looking into it for a while.

**Comment by J7mbo** [comment]
@Ocramius Ah yes, I was confusing FIG and phptherightway ;D Thansk for your response.

**Comment by XedinUnknown** [comment]
Hi! Sorry to bother 12 participants, but this seemed like the most appropriate place to ask this.

Nowhere in the inline or otherwise docs have I managed to find whether methods implementing `ContainerInterface#get()` return singletons, i.e. always the same instance, only initializing it on the first call. Or does this standard intentionally omit this? If so, I think this information should be included in the docs.

**Comment by mnapoli** [comment]
@XedinUnknown Could you please open a new issue? It's a different discussion, and people involved in this one might not be interested in this new one (especially since it involves a lot of people)
