### ISSUE TITLE
Clarify dependency resolution in delegate lookup feature

### ISSUE THREAD

**Issue by aztech-dev** [container-interop/container-interop#30]
The specification is not very clear with regards to the behavior a container should have when looking up a dependency in a delegate container when the delegate container does not contain the dependency. While the answer seems obvious, I would like A) to clarify that my understanding is correct and B) depending on the answer to A, suggest to amend the specification to clarify the expected behavior.

Assuming we are trying to fetch an object `A` with dependencies `B` and `C` from a container `Main` in which a delegate container `Child` was set, and where `B` is defined in `Child`, `C` in `Main`:

- `A` is requested from `Main`
- Main needs `B` and `C` to build `A`
   - `Main` delegates resolution of `B` to `Child`, which successfully returns its value.
   - `Main` delegates resolution of `C` to `Child`, which cannot resolve it and throws a NotFoundException.

At that point, am I correct in assuming that `Main` is allowed to catch the NotFoundException and perform the lookup on itself instead of failing with a NotFoundException ? Or am I totally mistaken ?

In either case, I think the delegate feature should be clarified with regards to the expected behavior for failed lookups in delegate containers, as I believe it should be possible to implement it without having to go through all the discussions/articles that have lead to the spec as it currently stands...

This is by no means a critic (I fully adhere to the interop idea and find it a great initiative), just a question as a total outsider to all of the discussions that have been taking place -- and possibly a fresh eye on the specification.

**Comment by mnapoli** [comment]
> At that point, am I correct in assuming that Main is allowed to catch the NotFoundException and perform the lookup on itself instead of failing with a NotFoundException ?

No :)

The idea of the delegate container is not the one of a *child* container (or sub-container).

Simply put: **the delegate container is the one we use to get dependencies.** That's it. Dependency not found? Nothing much to do except throw an exception…

For example. With 1 container, the container is calling itself: the delegate container **is itself**. So dependency not found: throw an exception. It doesn't make sense to look into "itself" since it already did.

Code-wise, it means replacing `$this->get($subDependency)` with `$this->delegateContainer->get($subDependency)`. And by default you can init `$this->delegateContainer = $this` in the constructor. Of course that's just an example of implementation, the standard doesn't constrain how you implement it :)

**Comment by mnapoli** [comment]
And in real situations with 2 containers, what you usually do is have a **root container** that wraps the 2 containers.

Sub-containers have the root container as "delegate", so when they call the delegate they are actually calling the 2nd container **and** themselves (in the order defined in the root container).

But again, that's just an example. It's just the common use case.

**Comment by aztech-dev** [comment]
Thank you for the clear and detailled answer. Guess that raises any doubts I had :)

**Comment by mnapoli** [comment]
Glad to know :)
