### ISSUE TITLE
What is the expected behavior of `has` for auto wiring capable DI containers?

### ISSUE THREAD

**Issue by simensen** [container-interop/container-interop#37]
Laravel's container, for example, is capable of instantiating many classes automatically even if they are not bound directly to the container. So the implementation in Acclimate would fail to return `true` for `has` even though a call to `get` would likely result in a successful operation.

 * https://github.com/jeremeamia/acclimate-container/blob/master/src/Adapter/LaravelContainerAdapter.php#L43

What is the expected behavior in these cases? If there is expected behavior, is it documented anywhere? I'm not super familiar with the spec yet but on wanting to try to use it I ran into this pretty fast. :)

**Comment by mnapoli** [comment]
The phpdoc say:

> Returns true if the container can return an entry for the given identifier.

So in theory an autowiring container should return `true` if a call to `get()` would be successful. In practice it's not always easy. Maybe this is also an issue with the adapter you linked to? In the `get()` implementation we can see it tries to `make()` the entry and silently fallback if that didn't succeed. This strategy (for get() or has()) is obviously not efficient, so that's why it's not really easy to implement.

FYI I ran into the same issue in PHP-DI: I tried to come up with a compromise between performances and "correct behavior": https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Definition/Resolver/ObjectCreator.php#L90 It basically checks that the entry is bound to a class that can be instantiated. The creation of the object can however fail later (e.g. you bound a wrong constructor parameter) but that's not checked in `has()`. It's subject to improvements, but until now it has never been an issue.

**Comment by shochdoerfer** [comment]
Maybe we need to clarify what checks the has() method has to do. Simply check if there is "something" there which can potentially be built or the more comprehensive check if the requested item can be constructed with all of it`s dependencies.

**Comment by moufmouf** [comment]
Hi all,

Actually, the issue has already been discussed here: https://groups.google.com/d/msg/php-fig/o_jFaRoLfAo/2qCQeRcQTb8J

We certainly need to make the `has` definition more clean. Here is my thought on this (mostly copy-pasted from my message on the FIG mailing list):

If `has($id)` returns true, it does not mean the `get($id)` will not throw an exception. It does however mean that `get($id)` should not throw a `NotFoundException`.

Here is a sample based on PimpleInterop (pimple extended to implement ContainerInterface)

```php
$pimpleInterop = new PimpleInterop();
$pimpleInterop['service'] = $pimpleInterop->share(function() {
    throw new \Exception('boom!');
});

// Should return true:
$pimpleInterop->has('service');

// Will throw an exception
$pimpleInterop->get('service');
```

A reflection-based auto-wiring containers could take the same route:

If the container assumes that it should be able to create any class *provided it is correctly configured*, then if the class exists, `has` could return true.
If one of the dependencies cannot be instanciated, when `get` is called, a "misconfiguration exception" is triggered. (the container considers it should be able to auto-wire the instance, provided the correct configuration was given).

Of course, the container could also try to fetch the complete list of dependencies when `has` is called and return true only if the instance is possible to retrieve. This is an implementation detail. It really depends on the philosophy of the container.

The important part is that we must allow `has` to return true and `get` to throw an exception if there is a misconfiguration. What a "misconfiguration" is really depends on the container.

**Comment by codeliner** [comment]
> Simply check if there is "something" there which can potentially be built

IMO this check is enough. If for whatever reason the creation of the dependency fails it is likely a problem I want to know as a developer.

**Comment by codeliner** [comment]
oh @moufmouf  was faster. :+1: absolutely agree

**Comment by shochdoerfer** [comment]
Sounds good to me as well.

**Comment by mnapoli** [comment]
> If `has($id)` returns true, it does not mean the `get($id)` will not throw an exception. It does however mean that `get($id)` should not throw a `NotFoundException`.

Perfect explanation, makes a lot of sense. Maybe I spoke too fast in my first comment ;)

**Comment by moufmouf** [comment]
Ok, I think we all agree on the correct behaviour of `has`.

Since this is the second time the question is asked, I guess we should improve the wording of the `has` definition in the documentation (or in the meta doc).

I'll keep this issue open until we improve the doc.

**Comment by simensen** [comment]
Alright, thanks for the feedback, everyone! I think I'll feel safe adding some additional checks to my implementation, then. Likely something along the lines of:

```php
return $this->container->bound($id) || (new ReflectionClass($id))-> isInstantiable();
```

I'll also make sure that I do not throw a `NotFoundException` in `get` if it does indeed blow up when I try to do that.

**Comment by mnapoli** [comment]
Maybe worth to do a PR to add that to Acclimate? (maybe that's what you implied?)

**Comment by simensen** [comment]
@mnapoli I'll probably send a PR to Acclimate as well. I'm not planning on using Acclimate myself as I have my own standalone Laravel container adapter.

**Comment by mnapoli** [comment]
I did a PR to improve the wording: #45

**Comment by Ocramius** [comment]
Solved via #45.

**Comment by glen-84** [comment]
Just to clarify, am I correct in saying that auto-wiring containers should return `true` for all calls to `has`?

I ask because of [this](https://github.com/auraphp/Aura.Di/issues/112).

**Comment by moufmouf** [comment]
I'd say it this way:

If an auto-wiring container decides to return `true` for any call where the ID is a non abstract class name, it is ok. It just means that the container things it should be able to instantiate any class out there and that if it cannot, it is because the user failed to configure it properly.

Another auto-wiring container might decide to do differently. For instance it is also ok for a container to check its internal configuration and return `true` only if the container has enough information to instantiate the entry. In this case, it means that the container considers that a class that is not configured at all is basically "unknown" to the container.

So it really depends on the container. The important thing is that a call to `has` might return true, and still, a call to  `get` might fail because of misconfiguration. What "misconfiguration" is depends on the implementing container.

Why is this this way? Because otherwise, on each `has` call, the container would need to call `get` to check that no exception is thrown. Which would defeat the purpose of `has`, and which would be very bad for performance.

**Comment by mnapoli** [comment]
> If an auto-wiring container decides to return true for any call where the ID is a non abstract class name, it is ok.

:+1: `has()` on an interface/abstract class that is not configured in the container should return false.

Also `has()` should obviously return false if the entry name is not a class/interface name (e.g. `$container->has('foo-bar-baz')` and the entry doesn't exist.

**Comment by glen-84** [comment]
@moufmouf Okay, so Aura.Di's implementation is acceptable then I guess.

Would you be open to an RFC for a new `tryGet($id, $default = null)` method? The name is unimportant at this stage, the idea is just to request a service and receive `null` or a default value if it cannot be resolved, instead of an exception. I believe that this type of thing is supported by a number of .NET containers ([ref](https://github.com/ServiceStack/ServiceStack/wiki/The-IoC-container) [search for "TryResolve"]).

**Comment by Ocramius** [comment]
>  and receive `null`

Since `tryGet` is a method that may fail, why not allow the method to just throw an exception, so that a very specific message (on why the `try` failed) can be used? I'd say that `tryGet` could return `$default` in cases when a service wasn't found, but not when a service is mis-configured (for example, a faulty DB connection configuration causing a low-level db exception)

**Comment by glen-84** [comment]
@Ocramius I'm okay with it throwing exceptions if there is misconfiguration, though I haven't spent too much time thinking about it yet. =)

**Comment by glen-84** [comment]
@Ocramius Err, wait. Would this include a missing param in the case of auto-wiring?

The idea is to be able to say "if you can (auto-)resolve this, return it, otherwise just return a default". You wouldn't want an exception just because of a missing param.

**Comment by Ocramius** [comment]
> You wouldn't want an exception just because of a missing param.

I actually would - it would mostly unexpected to get something different from what I configured, just because some parameter at the 10th level of indirection failed

**Comment by glen-84** [comment]
@Ocramius See my edit. Would you also expect exceptions in the auto-wiring case? It would kind of defeat the purpose of `tryGet` I think.

**Comment by Ocramius** [comment]
> would you also expect exceptions in the auto-wiring case?

Yes. Having things fallback/auto-fix-themselves is one of the reasons why `Zend\Di` ended up being unusable and totally impossible to understand.

**Comment by glen-84** [comment]
It's not auto-fixing anything – if it can't construct the object it tells you so with a `null` instead of an exception, which can then be handled in your code.

If you can't use `has` because it's implementation-specific, and `tryGet` will throw exceptions anyway, then there is no way to get a service that may or may not be resolvable without an exception.

Since it is *expected* that the service may not be resolvable, isn't it by definition *not* an exception?

__Disclaimer:__ I have a headache, so I may not be making any sense. =)

**Comment by Ocramius** [comment]
That's kind of the problem of auto-wiring containers btw: since they are wiring logic for you, they may do mistakes. `ShrödingersContainerInterface`

**Comment by drealecs** [comment]
> a `null` instead of an exception, which can then be handled in your code.
IMO, these are just to different ways to return from a method and can be handled with equal amount of effort in your code. There is no reason to have an extra method in the interface.

So, the relation between `has` and `get` is like this?:
If `has()` returns false, a call to `get()` throws an exception.
If `get()` successfully returns an entry from the container, a call to `has()` returns true.

**Comment by Ocramius** [comment]
See #65 about that
