### ISSUE TITLE
Simple question: why?

### ISSUE THREAD

**Issue by garrettw** [container-interop/container-interop#53]
Can someone explain to me the philosophical reasons for trying to standardize DICs? I've been wondering for a while.
As in, why do they need to be interoperable? It seems to me that the differences between each of the APIs out there are crucially important when it comes to selecting one that fits your individual requirements or style.

Related to this, I've followed issues on two particular DICs where this "interop" idea has been discussed (Dice and Auryn) and neither of those projects agree that this standard is a terribly useful thing. Auryn has outright refused to implement it, and Dice simply created a separate repo for those who want the interop adapter.

Auryn thread: https://github.com/rdlowrey/auryn/issues/77#issuecomment-88131140
Dice thread: Level-2/Dice#59

**Comment by Anahkiasen** [comment]
Biggest benefit to me is it would allow agnostic packages to create service providers that can then be used with any container and as such, virtually any framework (depending on the package of course).

**Comment by aztech-dev** [comment]
One valid use case I've personally had is when working with the Silex micro-framework. It is highly coupled to Pimple (which I personally highly dislike), so I ended up using another DIC in my app. Given the high coupling between Silex and Pimple, however, I still needed to resolve some dependencies defined in the Pimple container (ie. the router and url generator), and quite frankly, using the interop adapters made my life a whole lot easier, since it made it possible

**Comment by mnapoli** [comment]
Zend Expressive and Slim for example are 2 frameworks that use container-interop in order to avoid being tied to a specific container.

That allows users to switch the default container to one their prefer. For example Slim users can replace Pimple with another container which they'd rather use.

**Comment by shochdoerfer** [comment]
At first glance it seems wired but as @mnapoli already stated it totally makes sense in our "component thinking" to have an interface like this to be able to plug different implementations in and to not depend on one specific solution.

**Comment by jeremeamia** [comment]
I believe Aura's DI container and the League's DI container also use the interface.

**Comment by mnapoli** [comment]
Also regarding this part:

> It seems to me that the differences between each of the APIs out there are crucially important when it comes to selecting one that fits your individual requirements or style.

The API to get entries from a container is almost always the same. That's what the interface focuses on. Since this API is meant to be used by frameworks, that means it's mostly useful for frameworks.

On the other hand, the API to define entries varies greatly from container to container (closures, autowiring, YAML files, …) and that's indeed what makes the whole thing interesting for users. That's not the part that is meant to be standardized as of today.

**Comment by codeliner** [comment]
A great benefit for us (prooph core contributors) is that we can develop web-framework agnostic components but still can provide highly flexible factories which can be used in any framework supporting interop-container. So we don't need to waste time writing bundles, modules, providers, etc. and can focus on **real** features without coupling prooph components to one specific framework.
Container-interop is a great idea. It is a pity that this service locator discussion is blocking the PSR. Passing the container to an interop-factory like this [one](https://github.com/prooph/service-bus/blob/master/src/Container/AbstractBusFactory.php) has nothing to do with the service locator anti-pattern but is a great and easy way to set up components with configurable dependencies (combined with *interop-config*). Writing tests for the factories is as easy as `$container = $this->prophecy(ContainerInterface::class)`. So users can expect well tested set up logic. 
I hope interop-container become a PSR in the future and more people get used to it.

**Comment by garrettw** [comment]
Thanks for all the well-thought-out replies.
I guess the only thing I really disagree with is making the interface's name contain the word `Interface`. Regardless of how common that practice is, it seems a bit redundant and unnecessary if you're even slightly aware of the API.
But I'm sure it's probably too late to do anything about that, so oh well.

**Comment by mnapoli** [comment]
:wink: 

The `Interface` suffix is an internal convention of the FIG (internal because not in PSR-1 or PSR-2). The goal was to be in line with the FIG's practices to avoid any obstacle that could prevent container-interop from turning into a PSR. I'm not saying it's the best naming convention, but that's why it's that way.

**Comment by garrettw** [comment]
Ok, good to know.
