### ISSUE TITLE
List Auryn implementation in README?

### ISSUE THREAD

**Issue by elazar** [container-interop/container-interop#75]
I'm not sure if or where it makes sense to put this within the sections of the README listing libraries that implement the standard, but I recently created [a library](https://github.com/elazar/auryn-container-interop) that extends [Auryn](https://github.com/rdlowrey/Auryn) in order to add support for the standard to it, as the primary maintainer of Auryn has [expressed disinterest](https://github.com/rdlowrey/Auryn/issues/77#issuecomment-88177594) in adding that support.

**Comment by njasm** [comment]
hello @elazar , To me, it make's sense to add your library to the README if you feel it's right. Just like the Acclimate project was added. it's Adapters to known Containers using ArrayAccess.

To me it doesn't make sense to add Auryn, since the project himself, does not implement the interface/s
and as Your pointed out, there is disinterest in adding that support by the core developers/project owner.
 
My two cents.

**Comment by mnapoli** [comment]
:+1: feel free to send a pull request to add your project
